name: Android Build Workflow

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '选择构建类型'
        required: true
        type: choice
        options:
        - 'publishToMavenLocal'
        - 'assembleRelease'
        default: 'assembleRelease'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Execute Gradle Command
      run: |
        if [ "${{ github.event.inputs.build_type }}" = "publishToMavenLocal" ]; then
          ./gradlew publishToMavenLocal
        else
          ./gradlew assembleRelease
        fi
      
    - name: Upload Maven Local Repository
      if: github.event.inputs.build_type == 'publishToMavenLocal'
      uses: actions/upload-artifact@v4
      with:
        name: maven-local-repo
        path: ~/.m2/repository/
        
    - name: Upload AAR
      if: github.event.inputs.build_type == 'assembleRelease'
      uses: actions/upload-artifact@v4
      with:
        name: release-aar
        path: |
          **/build/outputs/aar/*.aar
          **/build/outputs/mapping/release/mapping.txt
